
services:
  # Label used to access the service container
  ldap:
    # Docker Hub image
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ports:
      # Maps LDAP ports on service container to the host
      - 10389:10389
      - 10636:10636