name: Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'public/dist/*.js'
      - 'public/dist/**/*.js'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'public/dist/*.js'
      - 'public/dist/**/*.js'

jobs:
  tests:

    runs-on: ${{ matrix.operating-system }}
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        operating-system: [ubuntu-20.04]
        php-versions: ['8.0', '8.1']
        sql-versions: ['mariadb', 'postgresql', 'sqlite']
        mode: ['dev', 'dist']

    name: PHP${{ matrix.php-versions }} - ${{ matrix.sql-versions }} - ${{ matrix.mode }}

    env:
      extensions: bcmath, curl, dom, gd, imagick, json, libxml, mbstring, pcntl, pdo, pdo_sqlite, pdo_mysql, pdo_pgsql, pgsql, sqlite3, zip
      key: cache-v1 # can be any string, change to clear the extension cache.

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      # Checks out a copy of your repository on the ubuntu machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@1.6.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache PHP Extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Cache Composer Dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug
          tools: pecl, composer

      - name: Set Up imagick & Exiftools
        run: |
          sudo apt-get update
          sudo apt-get --fix-broken install
          sudo apt-get -y install libimage-exiftool-perl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: setup Databases
        run: |
          sudo service mysql start
          touch database/database.sqlite
          mysql -uroot -proot -e 'create database homestead_test;'

      # begin of DEV
      - name: Install Composer dependencies (dev)
        if: ${{ matrix.mode == 'dev' }}
        run: composer install --prefer-dist --no-interaction

      - name: Check Syntax
        if: ${{ matrix.mode == 'dev' }}
        continue-on-error: ${{ matrix.php-versions != '8.0' }}
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --verbose --diff --dry-run

      - name: copy Env
        if: ${{ matrix.mode == 'dev' }}
        run: |
          cp .github/workflows/.env.${{ matrix.sql-versions }} .env

      - name: Generate secure key & Optimize application & Migrate
        if: ${{ matrix.mode == 'dev' }}
        run: |
          php artisan key:generate
          php artisan optimize
          php artisan migrate

      - name: Apply tests
        if: ${{ matrix.mode == 'dev' }}
        run: |
            echo .git/HEAD
            XDEBUG_MODE=coverage vendor/bin/phpunit --verbose

      - name: Codecov
        if: ${{ matrix.mode == 'dev' }}
        uses: codecov/codecov-action@v1

      - name: Make sure we can go backward
        if: ${{ matrix.mode == 'dev' }}
        run: php artisan migrate:rollback

      # end of DEV
      # begin of DIST
      - name: Install Composer dependencies (dist)
        if: ${{ matrix.mode == 'dist' }}
        run: composer install --prefer-dist --no-interaction --no-dev

      - name: Build Dist
        if: ${{ matrix.mode == 'dist' }}
        run: |
          make dist-clean

      - name: copy Env
        if: ${{ matrix.mode == 'dist' }}
        run: |
          cp .github/workflows/.env.${{ matrix.sql-versions }} Lychee/.env

      - name: setup MySQL Database with v3
        if: ${{ matrix.mode == 'dist' }}
        run: |
          mysql -uroot -proot homestead_test < .github/workflows/v3.sql

      - name: Generate secure key & Migrate & go backward
        if: ${{ matrix.mode == 'dist' }}
        run: |
          cd Lychee
          pwd
          php artisan key:generate
          php artisan migrate
          php artisan migrate:rollback
      # end of DIST
